version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306

volumes:
  database:
